[package]
name = "quick-api-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json"] }
serde = "1.0.208"
serde_json = "1.0.125"
thiserror = "1.0.63"
tokio = { version = "1.39.3", features = ["macros"] }
tokio-macros = "2.4.0"
